# Generated by Django 3.2.9 on 2021-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and time of the appointment')),
                ('price', models.PositiveIntegerField(verbose_name='Price of the appointment')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Completed without issue'), (2, 'Completed with issues'), (3, 'Client did not show up')], null=True, verbose_name='Status of the appointment')),
            ],
        ),
    ]
